package com.regula.sdk.enums;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/***
 * Class, contains fields, describing status codes, returned as a result of MRZ detection
 */
public class MRZDetectorErrorCode {
    @Retention(RetentionPolicy.SOURCE)
    @IntDef(value = {MRZ_DETECTED, ENABLE_ALLOCATE_MEMORY, INPUT_CONTAINER_NULL_POINTER, OUTPUT_CONTAINER_NULL_POINTER, NO_GOOD_INPUT_IMAGE_FOUND, NO_DETECTION, NO_CLASSIFER_LOADED_RECOGN_IMPOSSIBLE,
    BAD_MRZ_SEGMENTATION, MRZ_RECOGNIZED_CONFIDENTLY, MRZ_RECOGNIZED_UNCONFIDENTLY, BAD_COMMAND, NO_INPUT_DOCUMENT_BOUNDS_FOUND, CONSECUTIVE_RESULTS_ARE_NOT_EQUAL,
    NO_DETECTION_MRZ_VERY_SMALL, NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_LEFT, NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_RIGHT, NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_TOP, NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_BOTTOM,
    NO_DETECTION_MRZ_IS_OUT_OF_FOCUS, NO_RECOGNITION_MRZ_IS_OUT_OF_FOCUS, NO_RECOGNITION_STRONG_PERSPECTIVE, NO_RECOGNITION_MRZ_IS_VERY_SMALL})
    public @interface MrzDetectorCodes{}

    @MRZDetectorErrorCode.MrzDetectorCodes
    public static int getCode(int code){
        return code;
    }

    public static final int MRZ_DETECTED = 0,
    ENABLE_ALLOCATE_MEMORY = 1,
    INPUT_CONTAINER_NULL_POINTER = 2,
    OUTPUT_CONTAINER_NULL_POINTER = 3,
    NO_GOOD_INPUT_IMAGE_FOUND = 4,
    NO_DETECTION = 5,//на картинке нет мрз ни в каком виде
    NO_CLASSIFER_LOADED_RECOGN_IMPOSSIBLE = 6,
    BAD_MRZ_SEGMENTATION = 7,
    MRZ_RECOGNIZED_CONFIDENTLY = 8,
    MRZ_RECOGNIZED_UNCONFIDENTLY = 9,
    BAD_COMMAND = 10,
    NO_INPUT_DOCUMENT_BOUNDS_FOUND=11,
    CONSECUTIVE_RESULTS_ARE_NOT_EQUAL=12,

    NO_DETECTION_MRZ_VERY_SMALL=13,
    NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_LEFT=14,
    NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_RIGHT = 15,
    NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_TOP = 16,
    NO_DETECTION_MRZ_IS_VERY_CLOSE_TO_BOTTOM = 17,
    NO_DETECTION_MRZ_IS_OUT_OF_FOCUS = 18,
    NO_RECOGNITION_MRZ_IS_OUT_OF_FOCUS =19,
    NO_RECOGNITION_STRONG_PERSPECTIVE=20,
    NO_RECOGNITION_MRZ_IS_VERY_SMALL=21;
}
